#!/bin/bash
#SBATCH --job-name dataharmon_sims      # Set a name for your job. This is especially useful if you have multiple jobs queued.
#SBATCH --partition student     		# Slurm partition to use
#SBATCH --nodes 1 			 			#Number of nodes required 
#SBATCH --ntasks 12          			# Number of tasks to run. By default, one CPU core will be allocated per task
#SBATCH --time 0-05:00        			# Wall time limit in D-HH:MM
#SBATCH --mem-per-cpu=100     			# Memory limit for each tasks (in MB)
#SBATCH -o myscript_%j.out    			# File to which STDOUT will be written
#SBATCH -e myscript_%j.err    			# File to which STDERR will be written
#SBATCH --mail-type=ALL       			# Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=stevewr@uw.edu # Email to which notifications will be sent
 
module load R
R CMD BATCH TestParallel.R